name: Build Caddy

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '22 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - module:     ''
            asset_name: caddy
            job_name:   'Build Caddy'

          - module:     github.com/silinternational/certmagic-storage-dynamodb/v3
            asset_name: caddy-with-dynamodb
            job_name:   'Build Caddy with DynamoDB'

          - module:     github.com/ss098/certmagic-s3
            asset_name: caddy-with-s3
            job_name:   'Build Caddy with S3'

    name:    ${{ matrix.job_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run:  docker build -f docker/Dockerfile -t latest .

      - name: Run Docker container
        run:  docker run --name caddy_builder latest "${{ matrix.module }}"

      - name: Copy Caddy executable from Docker image
        run:  docker cp caddy_builder:/build/caddy ./caddy

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name:           ${{ matrix.asset_name }}
          path:           ./caddy
          retention-days: 1

  release:
    needs:   build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    name:    Release

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Set release tag environment variable
        run:  |
              echo "RELEASE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Check files
        run:  ls -al -R

      - name: Check files
        run:  |
              mv artifacts/caddy/caddy ./caddy
              mv artifacts/caddy-with-dynamodb/caddy ./caddy-with-dynamodb
              mv artifacts/caddy-with-s3/caddy ./caddy-with-s3

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name:     ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          files:    |
                    ./caddy
                    ./caddy-with-dynamodb
                    ./caddy-with-s3