name: Build Caddy

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '22 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - module:     ''
            asset_name: caddy
            job_name:   'Build Caddy'

          - module:     github.com/silinternational/certmagic-storage-dynamodb/v3
            asset_name: caddy-with-dynamodb
            job_name:   'Build Caddy with DynamoDB'

          - module:     github.com/ss098/certmagic-s3
            asset_name: caddy-with-s3
            job_name:   'Build Caddy with S3'

    name:    ${{ matrix.job_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        #        run:  docker build - --build-arg="MODULE=${{ matrix.module }}" < docker/build-caddy.sh
        run:  docker build -f docker/Dockerfile -t latest .

      - name: Run Docker container
        run:  docker run --name caddy_builder latest "${{ matrix.module }}"

      - name: Copy Caddy executable from Docker image
        run:  docker cp caddy_builder:/build/caddy ./caddy

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name:           ${{ matrix.asset_name }}
          path:           ./caddy
          retention-days: 1

  release:
    needs:   build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    name:    Release

    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name:     ${{ github.sha }}
          tag_name: ${{ github.sha }}
          files:    |
                    caddy
                    caddy-with-dynamodb
                    caddy-with-s3