name: Build Caddy

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '22 11 * * *'

jobs:
  build:
    name:    Build Caddy

    strategy:
      matrix:
        include:
          - module:     ''
            asset_name: caddy

          - module:     github.com/ss098/certmagic-s3
            asset_name: caddy-with-s3

          - module:     github.com/silinternational/certmagic-storage-dynamodb/v3
            asset_name: caddy-with-dynamodb

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        #        run:  docker build - --build-arg="MODULE=${{ matrix.module }}" < docker/build-caddy.sh
        run:  docker build -f docker/Dockerfile -t latest .

      - name: Run Docker container
        run:  docker run --name caddy_builder latest "${{ matrix.module }}"

      - name: Copy Caddy executable from Docker image
        run:  docker cp caddy_builder:/build/caddy ./caddy

      - name: A
        run:  ls -al .

      - name: B
        run:  pwd

      - name: Upload executable to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file:       ./caddy
          asset_name: ${{ matrix.asset_name }}
          tag:        ${{ github.ref }}